// Generated by CoffeeScript 1.6.3
(function() {
  var AccessToken;

  AccessToken = (function() {
    function AccessToken(props) {
      if (props == null) {
        props = {};
      }
      this.userId = props.userId;
      this.clientId = props.clientId;
      this.type = props.type;
      this.value = props.value;
      this.expiresAt = props.expiresAt;
      this.refreshToken = props.refreshToken;
    }

    AccessToken.prototype.expireIn = function(ms) {
      var currentTime, expiresAt;
      if (ms == null) {
        ms = 0;
      }
      currentTime = new Date().getTime();
      expiresAt = currentTime + ms;
      return this.expiresAt = new Date(expiresAt);
    };

    AccessToken.prototype.isExpired = function(currentDate) {
      var expirationDate;
      if (this.expiresAt == null) {
        return false;
      }
      if (currentDate == null) {
        currentDate = new Date();
      }
      expirationDate = new Date(this.expiresAt);
      return currentDate > expirationDate;
    };

    return AccessToken;

  })();

  module.exports = AccessToken;

}).call(this);

/*
//@ sourceMappingURL=AccessToken.map
*/
