// Generated by CoffeeScript 1.6.3
(function() {
  var AccessToken;

  AccessToken = (function() {
    function AccessToken(props) {
      if (props == null) {
        props = {};
      }
      this.userId = props.userId;
      this.clientId = props.clientId;
      this.type = props.type;
      this.value = props.value;
      this.expiresIn = props.expiresIn;
      this.createdAt = props.createdAt;
      this.refreshToken = props.refreshToken;
      this.hasBeenRefreshed = props.hasBeenRefreshed;
      this.setDefaults();
    }

    AccessToken.prototype.setDefaults = function() {
      if (this.createdAt == null) {
        this.createdAt = new Date();
      }
      return this.hasBeenRefreshed != null ? this.hasBeenRefreshed : this.hasBeenRefreshed = false;
    };

    AccessToken.prototype.getCreationDate = function() {
      if (this.createdAt instanceof Date) {
        return this.createdAt;
      }
      return new Date(this.createdAt);
    };

    AccessToken.prototype.getExpirationDate = function() {
      var creationDate, expirationMs;
      if (!this.expiresIn) {
        return void 0;
      }
      creationDate = this.getCreationDate();
      expirationMs = creationDate.getTime() + this.expiresIn;
      return new Date(expirationMs);
    };

    AccessToken.prototype.isExpired = function(currentDate) {
      if (currentDate == null) {
        currentDate = new Date();
      }
      return currentDate > this.getExpirationDate();
    };

    return AccessToken;

  })();

  module.exports = AccessToken;

}).call(this);

/*
//@ sourceMappingURL=AccessToken.map
*/
