// Generated by CoffeeScript 1.6.3
(function() {
  exports.AccessTokenService = require('./AccessTokenService');

  exports.AccessToken = require('./AccessToken');

  exports.AccessTokenRepository = require('./AccessTokenRepository');

  exports.createService = function(config) {
    return new exports.AccessTokenService(config);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
