// Generated by CoffeeScript 1.6.3
(function() {
  var day, hour, minute, second, week;

  second = 1000;

  minute = 60 * second;

  hour = 60 * minute;

  day = 24 * hour;

  week = 7 * day;

  module.exports = {
    second: second,
    minute: minute,
    hour: hour,
    day: day,
    week: week
  };

}).call(this);

/*
//@ sourceMappingURL=TimeInMs.map
*/
