// Generated by CoffeeScript 1.6.3
(function() {
  var MemoryAccessTokenRepository;

  MemoryAccessTokenRepository = (function() {
    function MemoryAccessTokenRepository(props) {
      if (props == null) {
        props = {};
      }
      this.collection = props.collection;
      this.refreshTokenIndex = props.refreshTokenIndex;
      this.setDefaults();
    }

    MemoryAccessTokenRepository.prototype.setDefaults = function() {
      if (this.collection == null) {
        this.collection = {};
      }
      return this.refreshTokenIndex != null ? this.refreshTokenIndex : this.refreshTokenIndex = {};
    };

    MemoryAccessTokenRepository.prototype.store = function(accessToken, callback) {
      this.collection[accessToken.value] = accessToken;
      this.refreshTokenIndex[accessToken.refreshToken] = accessToken.value;
      return callback(null, accessToken);
    };

    MemoryAccessTokenRepository.prototype.find = function(value, callback) {
      var accessToken;
      accessToken = this.collection[value];
      return callback(null, accessToken);
    };

    MemoryAccessTokenRepository.prototype.findByRefreshToken = function(refreshToken, callback) {
      var accessToken, value;
      value = this.refreshTokenIndex[refreshToken];
      if (value == null) {
        return callback(null, null);
      }
      accessToken = this.collection[value];
      return callback(null, accessToken);
    };

    return MemoryAccessTokenRepository;

  })();

  module.exports = MemoryAccessTokenRepository;

}).call(this);

/*
//@ sourceMappingURL=Memory.map
*/
